/**
 * Templates for `g generator` and `g task`. The generator scaffold depends
 * on `next-wee` for types only, so it runs before the package is installed
 * as a runtime dependency; the helpers it needs are inlined.
 */
import { camelCase, kebabCase, pascalCase, plural } from "../lib/inflect.js"

/** `tools/generators/<name>/index.ts`. */
const customGeneratorTemplate = (name: string): string => {
  const kebab = kebabCase(name)
  const dir = plural(kebab)
  return `/**
 * \`wee g ${kebab} <Name>\`: writes ${dir}/<name>.ts from templates/${kebab}.ts.tpl.
 * The template tokens are __Name__ (PascalCase) and __name__ (camelCase).
 * Add args below; they parse like the built-in generators. The CLI applies
 * the changes, so --dry-run, --json and \`wee destroy ${kebab} <Name>\` need
 * no code here.
 */
import { readFileSync } from "node:fs"
import { join } from "node:path"
import type { GeneratorDef } from "next-wee"

const words = (value: string): string[] =>
  value
    .replace(/([a-z0-9])([A-Z])/g, "$1 $2")
    .split(/[^A-Za-z0-9]+/)
    .filter((word) => word.length > 0)
    .map((word) => word.toLowerCase())
const kebab = (value: string): string => words(value).join("-")
const pascal = (value: string): string =>
  words(value)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join("")
const camel = (value: string): string => {
  const name = pascal(value)
  return name.charAt(0).toLowerCase() + name.slice(1)
}

const args = {
  name: {
    type: "positional",
    description: "${pascalCase(name)} name, e.g. Example",
    required: true,
  },
} as const

const render = (name: string): string =>
  readFileSync(join(import.meta.dirname, "templates", "${kebab}.ts.tpl"), "utf8")
    .replaceAll("__Name__", pascal(name))
    .replaceAll("__name__", camel(name))

const generator: GeneratorDef<typeof args> = {
  name: "${kebab}",
  description: "Custom ${kebab} generator",
  args,
  manifestName: (parsed) => pascal(parsed.name),
  run: async (ctx, parsed) => [
    {
      kind: "create",
      path: join(
        ctx.config.srcDir ? "src" : ".",
        "${dir}",
        \`\${kebab(parsed.name)}.ts\`
      ),
      content: render(parsed.name),
    },
  ],
}

export { generator }
`
}

/** `tools/generators/<name>/templates/<name>.ts.tpl`. */
const customTemplateFile = (
  name: string
): string => `/** __Name__ ${kebabCase(name)}. Generated by \`wee g ${kebabCase(name)} __Name__\`. */
const __name__ = {
  name: "__Name__",
}

export { __name__ }
`

/** `tools/tasks/<name>.ts`. */
const taskTemplate = (name: string): string => {
  const fn = camelCase(name)
  return `/**
 * \`wee ${name}\`: runs with the app context preloaded (db, schema,
 * services, auth) and the args after the task name. Return false or
 * throw to exit 1.
 */
import type { TaskContext } from "next-wee"

const ${fn} = async ({ db, services, args }: TaskContext): Promise<boolean> => {
  process.stdout.write(
    \`${name}: db \${db === undefined ? "off" : "on"}, services \${Object.keys(services).join(", ") || "none"}, args \${args.join(" ") || "none"}\\n\`
  )
  return true
}

export { ${fn} as task }
`
}

export { customGeneratorTemplate, customTemplateFile, taskTemplate }
