/**
 * Migration files for the Prisma adapter. Prisma owns the up SQL through
 * `prisma migrate diff`. `generateMigration` diffs a scratch copy of the
 * schema folder before and after the pending changes, so the result is a
 * FileChange list: dry-run shows it, apply writes it, destroy reverses it.
 * The reverse diff sits beside the up SQL as `down.sql`; `db:rollback`
 * prints the manual procedure that uses it.
 */
import {
  cpSync,
  existsSync,
  mkdirSync,
  mkdtempSync,
  readdirSync,
  rmSync,
} from "node:fs"
import { join, relative } from "node:path"
import { format, formatISO, parse } from "date-fns"
import { x } from "tinyexec"
import type { SchemaChange } from "../../core/adapters.js"
import type { FileChange } from "../../core/changes.js"
import { applyChanges } from "../../core/changes.js"
import { CONFIG_DIR } from "../../core/config.js"
import type { Context } from "../../core/context.js"
import { WeeError } from "../../core/errors.js"
import { packageBin } from "../../lib/packages.js"
import { dbDirs } from "../shared.js"

const MIGRATION_DIR = /^(\d{14})_(.+)$/
const STAMP = "yyyyMMddHHmmss"
const LOCK_FILE = "migration_lock.toml"

/** Provider names Prisma writes into `migration_lock.toml`. */
const LOCK_PROVIDER: Record<string, string> = {
  postgres: "postgresql",
  sqlite: "sqlite",
  mysql: "mysql",
}

/** Migration folder names in order, e.g. `20260918120000_create_posts`. */
const listMigrations = (dir: string): string[] =>
  existsSync(dir)
    ? readdirSync(dir, { withFileTypes: true })
        .filter(
          (entry) => entry.isDirectory() && MIGRATION_DIR.test(entry.name)
        )
        .map((entry) => entry.name)
        .sort()
    : []

/** ISO timestamp from the 14-digit prefix of a migration folder name. */
const migrationTime = (name: string): string => {
  const stamp = name.match(MIGRATION_DIR)?.[1] ?? ""
  return formatISO(parse(stamp, STAMP, new Date()))
}

/** One side of a diff: a schema folder, a migrations folder or nothing. */
type DiffSide = { schema: string } | { migrations: string } | { empty: true }

const sideArgs = (prefix: "from" | "to", side: DiffSide): string[] => {
  if ("schema" in side) {
    return [`--${prefix}-schema`, side.schema]
  }
  if ("migrations" in side) {
    return [`--${prefix}-migrations`, side.migrations]
  }
  return [`--${prefix}-empty`]
}

interface DiffOptions {
  ctx: Context
  from: DiffSide
  to: DiffSide
}

/**
 * Runs `prisma migrate diff --script` and returns the SQL, or undefined when
 * the two sides match. Prisma exits 2 for a non-empty diff with `--exit-code`.
 */
const diffSql = async (options: DiffOptions): Promise<string | undefined> => {
  const { ctx, from, to } = options
  const target = ctx.target.path
  const result = await x(
    "node",
    [
      packageBin(target, "prisma"),
      "migrate",
      "diff",
      ...sideArgs("from", from),
      ...sideArgs("to", to),
      "--script",
      "--exit-code",
    ],
    { nodeOptions: { cwd: target }, throwOnError: false }
  )
  if (result.exitCode === 0) {
    return undefined
  }
  if (result.exitCode !== 2) {
    throw new WeeError("prisma-failed", "prisma migrate diff failed", {
      exitCode: result.exitCode ?? 1,
      data: { stdout: result.stdout, stderr: result.stderr },
    })
  }
  return result.stdout
}

/** Runs `fn` with a scratch folder under `.app/` that is removed afterwards. */
const withScratch = async <T>(
  ctx: Context,
  fn: (scratch: string) => Promise<T>
): Promise<T> => {
  const configDir = join(ctx.target.path, CONFIG_DIR)
  const hadConfigDir = existsSync(configDir)
  mkdirSync(configDir, { recursive: true })
  const scratch = mkdtempSync(join(configDir, "wee-"))
  try {
    return await fn(scratch)
  } finally {
    rmSync(scratch, { recursive: true, force: true })
    if (!hadConfigDir) {
      rmSync(configDir, { recursive: true, force: true })
    }
  }
}

interface MigrationFiles {
  /** Folder name under the migrations dir. */
  folder: string
  up: string
  down: string
}

/** The three changes of one migration: up SQL, down SQL and the lock file. */
const migrationChanges = (
  ctx: Context,
  files: MigrationFiles
): FileChange[] => {
  const { migrationsDir } = dbDirs(ctx)
  const providerName = LOCK_PROVIDER[ctx.config.db?.provider ?? "postgres"]
  return [
    {
      kind: "create",
      path: join(migrationsDir, files.folder, "migration.sql"),
      content: files.up,
    },
    {
      kind: "create",
      path: join(migrationsDir, files.folder, "down.sql"),
      content: files.down,
    },
    {
      kind: "ensure",
      path: join(migrationsDir, LOCK_FILE),
      content: `# Please do not edit this file manually\n# It should be added in your version-control system (e.g., Git)\nprovider = "${providerName}"\n`,
    },
  ]
}

const CUSTOM_UP = "-- Custom migration. Write the SQL here.\n"
const CUSTOM_DOWN = "-- Down migration. Reverse the custom SQL here.\n"

interface GenerateOptions {
  ctx: Context
  name: string
  change: SchemaChange
  pending: FileChange[]
}

/** Diffs the schema folder against the pending changes and returns the migration as changes. */
const generateMigration = async (
  options: GenerateOptions
): Promise<FileChange[]> => {
  const { ctx, name, change, pending } = options
  const folder = `${format(new Date(), STAMP)}_${name}`
  if (change.kind === "custom") {
    return migrationChanges(ctx, { folder, up: CUSTOM_UP, down: CUSTOM_DOWN })
  }
  const target = ctx.target.path
  const { schemaDir } = dbDirs(ctx)
  return withScratch(ctx, async (scratch) => {
    const before = join(scratch, "before")
    const after = join(scratch, "after")
    for (const dir of [before, after]) {
      if (existsSync(join(target, schemaDir))) {
        cpSync(join(target, schemaDir), dir, { recursive: true })
      }
      mkdirSync(dir, { recursive: true })
    }
    const schemaPending = pending
      .filter((item) => !relative(schemaDir, item.path).startsWith(".."))
      .map((item) => ({
        ...item,
        path: join("after", relative(schemaDir, item.path)),
      }))
    applyChanges({ root: scratch, changes: schemaPending, dryRun: false })
    const up = await diffSql({
      ctx,
      from: { schema: before },
      to: { schema: after },
    })
    if (up === undefined) {
      throw new WeeError(
        "no-schema-changes",
        `${name}: the schema did not change, nothing to migrate`
      )
    }
    const down =
      (await diffSql({
        ctx,
        from: { schema: after },
        to: { schema: before },
      })) ?? ""
    return migrationChanges(ctx, { folder, up, down })
  })
}

export type { DiffSide }
export {
  diffSql,
  generateMigration,
  listMigrations,
  migrationChanges,
  migrationTime,
  STAMP,
}
